version: "3"
services:

  portfolio:
    image: garugaru/portfolio
    networks:
      - traefik
    deploy:
      labels:
        - traefik.docker.network=traefik
        - traefik.port=80
        - traefik.frontend.rule=Host:garu.io
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  traefik:
    external: true
  internal:
    external: false
