apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio
  namespace: garu-io
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: "garu.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: garu-io
            port:
              number: 80
  tls:
    - hosts:
        - garu.io
      secretName: garu-io-cert
