apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yml
- ingress.yml
- deployment.yml
images:
- name: garugaru/garu.io
  newName: garugaru/garu.io
  newTag: ebed50783f6cb461e917e68e75bbeaac3d67ed0b
